### ISSUE TITLE
sign crashes w/ fully-good cert,  key vault, creds

### ISSUE THREAD

**Issue by bc3tech** [vcsjones/OpenVsixSignTool#94]
I just simply ran this:

```
avxst sign -kvu https://my-vault.vault.azure.net/ -kvi 5ca7...85 -kvt 038...04 -kvc digicert-codesign .\My.Vsix\bin\Release\My.vsix -t http://timestamp.digicert.com -kvs "..."
```

and got unhandled exception output:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenVsixSignTool.Core.OpcContentTypes.ProcessElement(OpcContentTypeMode mode, XElement element) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcContentTypes.cs:line 122
   at OpenVsixSignTool.Core.OpcContentTypes..ctor(XDocument document, Boolean isReadOnly) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcContentTypes.cs:line 79
   at OpenVsixSignTool.Core.OpcPackage.ConstructContentTypes() in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcPackage.cs:line 285
   at OpenVsixSignTool.Core.OpcPackage.get_ContentTypes() in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcPackage.cs:line 57
   at OpenVsixSignTool.Core.OpcPackage.CreatePart(Uri partUri, String mimeType) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcPackage.cs:line 137        
   at OpenVsixSignTool.Core.OpcPackageSignatureBuilder.SignCore(String signatureFileName) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcPackageSignatureBuilder.cs:line 122
   at OpenVsixSignTool.Core.OpcPackageSignatureBuilder.SignAsync(AzureKeyVaultSignConfigurationSet configuration) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool.Core/OpcPackageSignatureBuilder.cs:line 58
   at OpenVsixSignTool.SignCommand.PerformAzureSignOnVsixAsync(String vsixPath, Boolean force, Uri timestampUri, HashAlgorithmName fileDigestAlgorithm, HashAlgorithmName timestampDigestAlgorithm, String azureUri, String azureTenantId, String azureClientId, String azureClientCertificateName, String azureClientSecret) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool/SignCommand.cs:line 277
   at OpenVsixSignTool.SignCommand.SignAzure(CommandOption azureKeyVaultUrl, CommandOption azureKeyVaultTenantId, CommandOption azureKeyVaultClientId, CommandOption azureKeyVaultClientSecret, CommandOption azureKeyVaultCertificateName, CommandOption force, CommandOption fileDigest, CommandOption timestampUrl, CommandOption timestampAlgorithm, CommandArgument vsixPath) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool/SignCommand.cs:line 201
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OpenVsixSignTool.Program.Main(String[] args) in /Users/olegz/Projects/AzureVsixSignTool/src/OpenVsixSignTool/Program.cs:line 79
```

**Comment by bc3tech** [comment]
looks like this is an issue with ordering of args to the azure tool
